[package]
name = "bt-gap"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
fdio = "0.2"
fidl = "0.1"
fidl_bluetooth_control = "0.1"
fidl_bluetooth_host = "0.1"
fidl_bluetooth_gatt = "0.1"
fidl_bluetooth_low_energy = "0.1"
fidl_bluetooth = "0.1"
fuchsia-bluetooth = "0.1"
fuchsia-vfs-watcher = "0.1"
futures = "0.2.1"
fuchsia-app = "0.1"
futures-core = "0.2.1"
fuchsia-async = "0.1"
fuchsia-zircon = "0.3"
log = "0.4"
parking_lot = "0.4"
structopt = "0.2.4"
