# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "wlan-hw-sim"
description = "WLAN hardware simulator"
version = "0.1.0"
license = "BSD-3-Clause"

[dependencies]
byteorder = "1.2"
failure = "0.1"
fidl_wlan_device = "0.1"
fidl_wlantap = "0.1"
fuchsia-async = "0.1"
fuchsia-zircon = "0.3"
futures = "0.2.0-alpha"
wlantap-client = "0.1"
