[package]
name = "luthier"
version = "0.1.0"
description = "Fidl instrospection"
authors = ["Benjamin Brittain <bwb@google.com>"]

[dependencies]
structopt = "0.2.4"
failure = "0.1.1"
fdio = "0.2"
fidl = "0.1"
futures-core = "=0.2.0-alpha"
futures = "=0.2.0-alpha"
fidl_luthier = "0.1.0"

# fuchsia-app = "0.1.0"
fuchsia-async = "0.1.0"
# fuchsia-zircon = "0.3.4"
# log = "0.4"
# simple_logger = "0.5"
# serde = "1.0"
# serde_derive = "1.0"
# serde_json = "1.0"
